/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.compiladorlenguajeespaneol.Grafico;

import javax.swing.JTextArea;

/**
 *
 * @author jose
 * dos entradas de texto
 */
public class EntradaSalida extends javax.swing.JPanel {
    
    private panelPrincipal panel;
    /**
     * Creates new form EntradaSalida
     */
    public EntradaSalida(panelPrincipal panel) {
        this.panel = panel;
        initComponents();
        NumeroLinea numero1 = new NumeroLinea(terminal);
        NumeroLinea numero2 = new NumeroLinea(entrada); 
    }

    public JTextArea getEntrada() {
        return entrada;
    }

    public void setEntrada(JTextArea entrada) {
        this.entrada = entrada;
    }

    public JTextArea getTerminal() {
        return terminal;
    }

    public void setTerminal(JTextArea terminal) {
        this.terminal = terminal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entrada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        terminal = new javax.swing.JTextArea();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        entrada.setBackground(new java.awt.Color(0, 0, 0));
        entrada.setColumns(20);
        entrada.setFont(new java.awt.Font("Kalimati", 3, 14)); // NOI18N
        entrada.setForeground(new java.awt.Color(0, 204, 204));
        entrada.setRows(5);
        entrada.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jScrollPane1.setViewportView(entrada);

        add(jScrollPane1);

        terminal.setBackground(new java.awt.Color(102, 102, 102));
        terminal.setColumns(20);
        terminal.setFont(new java.awt.Font("DejaVu Serif", 3, 14)); // NOI18N
        terminal.setForeground(new java.awt.Color(102, 0, 0));
        terminal.setRows(5);
        terminal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jScrollPane2.setViewportView(terminal);

        add(jScrollPane2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea entrada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea terminal;
    // End of variables declaration//GEN-END:variables
}
