/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.compiladorlenguajeespaneol.Grafico;


import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author jose
 */
public class panelPrincipal extends javax.swing.JPanel {
    
    private EntradaSalida centro;
    private Botones arriba;
    private Abajo abajo;

    /**
     * Creates new form panelPrincipal
     */
    public panelPrincipal() {
        centro = new EntradaSalida(this);
        arriba = new Botones(this);
        abajo = new Abajo();
//        derecha.setLayout(new CardLayout());
//        izquiera.setLayout(new CardLayout());
//        centro.setLayout(new CardLayout());
//        arriba.setLayout(new CardLayout());
//        abajo.setLayout(new CardLayout());
        initComponents();
        this.setLayout(new BorderLayout());
        agregarBotones();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    public void agregarBotones(){
        //EntradaSalida paso = new EntradaSalida();
       // Botones botones = new Botones();
        //Abajo abajoa = new Abajo();
        //abajo.add(abajoa);
        //arriba.add(botones);
        //centro.add(paso);
        
        agregar();
  
    }

    public EntradaSalida getCentro() {
        return centro;
    }

    public void setCentro(EntradaSalida centro) {
        this.centro = centro;
    }

    public Botones getArriba() {
        return arriba;
    }

    public void setArriba(Botones arriba) {
        this.arriba = arriba;
    }

    public Abajo getAbajo() {
        return abajo;
    }

    public void setAbajo(Abajo abajo) {
        this.abajo = abajo;
    }
    
 public void agregar() {
        this.add(centro, BorderLayout.CENTER);
        //this.add(derecha, BorderLayout.EAST);
        //this.add(izquiera, BorderLayout.WEST);
        this.add(arriba, BorderLayout.NORTH);
        this.add(abajo, BorderLayout.SOUTH);
        this.setVisible(false);
        this.setVisible(true);
    }
    public void setCentro(JPanel centro) {
        this.setVisible(false);
        this.centro.setVisible(false);
        //this.centro = new JPanel();
        this.centro.setLayout(new CardLayout());
        this.centro.add(centro);
        this.centro.setVisible(true);
        agregar();
    }
    
  //

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
