
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.mycompany.compiladorlenguajeespaneol.Flex_Y_Cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICAR = 12;
  public static final int MENOS = 13;
  public static final int COMILLASTEXTO = 20;
  public static final int PUNTOYCOMA = 21;
  public static final int DOSPUNTOS = 10;
  public static final int DECIMAL = 18;
  public static final int LEER = 3;
  public static final int POTENCIA = 15;
  public static final int FLOTANTE = 5;
  public static final int ID = 19;
  public static final int PARENTESISCERRADO = 8;
  public static final int COMILLAS = 9;
  public static final int PARENTESISABIERTO = 7;
  public static final int STRING = 6;
  public static final int COMA = 11;
  public static final int EOF = 0;
  public static final int ESCRIBIR = 2;
  public static final int NUMERO = 17;
  public static final int error = 1;
  public static final int DIAGONAL = 14;
  public static final int ENTERO = 4;
  public static final int MAS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ESCRIBIR",
  "LEER",
  "ENTERO",
  "FLOTANTE",
  "STRING",
  "PARENTESISABIERTO",
  "PARENTESISCERRADO",
  "COMILLAS",
  "DOSPUNTOS",
  "COMA",
  "MULTIPLICAR",
  "MENOS",
  "DIAGONAL",
  "POTENCIA",
  "MAS",
  "NUMERO",
  "DECIMAL",
  "ID",
  "COMILLASTEXTO",
  "PUNTOYCOMA"
  };
}

